#!/bin/bash
# This is an AppImage builder for ToastWallet on Linux
# Version: 1.0
# Date: 29 July 2019
# Author: Richard Holland

#flags to run with electon builder
EBFLAGS='-l'

#enables useful debugging output in electon builder
export DEBUG=electron-builder,electron-builder:*

#change these as needed for your certificate
export CSC_LINK=../../../codesign.p12
export CSC_KEY_PASSWORD=$1

if [ -z "$1" ]; then echo "Must supply certificate password as argument"; exit; fi

#clone the repo if needed
stat core >> /dev/null 2>&1
if [ "$?" -eq "0" ]; then
	echo "`pwd`/core exists, assuming this is the Toast Wallet core folder..."
else
	echo "can't find core folder, cloning repo..."
	git clone https://github.com/ToastWallet/core.git core
fi

cd core

# remove env css which android/PC can't handle
if [[ "`cat www/css/app.css | grep 'env(' | wc -l`" -gt "0" ]]; then
    mv www/css/app.css www/css/_app.css
    cat www/css/_app.css | sed -r 's/ *[-\+] *env\([^\)]+\)//img' > www/css/app.css
fi

#this plugin often causes problems due to its dangling URL_SCHEME variable, readding it each build is hacky and effective
phonegap plugin add cordova-plugin-customurlscheme --variable URL_SCHEME=xrpl
phonegap build browser

#copy the electron package.json to where electron builder can find it
cp electron_package.json platforms/browser/package.json
cp manifest.webapp electron-start.js platforms/browser/

cd platforms/browser

#clean up any existing build and unwanted additional index.html that sits www/../
rm -rf build index.html dist

#build
electron-builder $EBFLAGS

cd ../../../

